apiVersion: apps/v1
kind: Deployment
metadata:
  name: dphome
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: nginx-multi
  template:
    metadata:
      labels:
        app: nginx-multi
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: HTTP_PORT
          value: "80"
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"