apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  selector:
    app:  nginx-multi
  ports:
  - name: nginx
    port: 80
    nodePort: 30080
    protocol: TCP
  - name: multitool
    port: 8080
    nodePort: 30081
    protocol: TCP
  type: NodePort
