apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
spec:
  selector:
    app: nginx-multi
  ports:
  - name: nginx
    port: 9001 
    targetPort: 80
    protocol: TCP
  - name: multitool
    port: 9002
    targetPort: 8080
    protocol: TCP